const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { PGlite } = require('@electric-sql/pglite');

test('atomic loyalty: permissions, retries, rewards, reversals and rollback', async t => {
    const db = new PGlite();
    t.after(() => db.close());
    const admin='00000000-0000-0000-0000-000000000001';
    const customer='00000000-0000-0000-0000-000000000002';
    await db.exec(`
      CREATE ROLE anon; CREATE ROLE authenticated;
      CREATE SCHEMA auth;
      CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
        $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      GRANT USAGE ON SCHEMA auth TO anon,authenticated;
      CREATE TABLE admins(id uuid PRIMARY KEY);
      INSERT INTO admins VALUES ('${admin}');
      CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path='' AS
        $$ SELECT EXISTS(SELECT 1 FROM public.admins WHERE id=auth.uid()) $$;
      CREATE TABLE clientas(id uuid PRIMARY KEY,usuario text NOT NULL UNIQUE,nombre text NOT NULL,telefono text,visitas integer);
      CREATE TABLE citas(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cliente_id uuid REFERENCES clientas(id) ON DELETE CASCADE,fecha date NOT NULL,hora time NOT NULL,
        estado text,duracion_minutos integer,servicio text,nombre_cliente text,telefono text,precio numeric(10,2));
      ALTER TABLE citas ADD CONSTRAINT no_overlap EXCLUDE USING gist(
        tsrange(fecha+hora,fecha+hora+make_interval(mins=>coalesce(duracion_minutos,30)),'[)') WITH &&
      ) WHERE (coalesce(estado,'pendiente')<>'cancelada');
      INSERT INTO clientas VALUES ('${customer}','prueba','Clienta','000',8);
      INSERT INTO citas(id,cliente_id,fecha,hora,estado,duracion_minutos) VALUES
        (50,'${customer}','2026-01-01','09:00','completada',30),
        (100,'${customer}','2030-01-01','09:00','confirmada',30),
        (101,'${customer}','2030-01-01','10:00','confirmada',30),
        (102,'${customer}','2030-01-01','11:00','confirmada',30),
        (103,'${customer}','2030-01-01','12:00','confirmada',30);
      ALTER TABLE clientas ENABLE ROW LEVEL SECURITY;
      ALTER TABLE citas ENABLE ROW LEVEL SECURITY;
      CREATE POLICY admin_clientas ON clientas FOR ALL USING(public.is_admin());
      CREATE POLICY own_clientas ON clientas FOR SELECT USING(id=auth.uid());
      CREATE POLICY admin_citas ON citas FOR ALL USING(public.is_admin());
      CREATE POLICY own_citas ON citas FOR INSERT WITH CHECK(cliente_id=auth.uid());
      GRANT SELECT,INSERT,UPDATE,DELETE ON clientas,citas TO authenticated;
      GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
      CREATE TABLE resenas(cliente_id uuid,destacada boolean);
      ALTER TABLE resenas ENABLE ROW LEVEL SECURITY;
      CREATE POLICY "Resenas lectura publica" ON resenas FOR SELECT USING(true);
      CREATE POLICY "Resenas insert clientas" ON resenas FOR INSERT TO authenticated WITH CHECK(true);
      CREATE FUNCTION public.citas_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
      BEGIN
        IF NOT public.is_admin() THEN
          IF TG_OP='INSERT' THEN NEW.estado := 'pendiente';
          ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN RAISE EXCEPTION 'No autorizado a cambiar el estado'; END IF;
        END IF;
        RETURN NEW;
      END $$;
      CREATE FUNCTION public.clientas_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
      BEGIN
        IF NOT public.is_admin() THEN
          IF TG_OP='INSERT' THEN NEW.visitas := 0;
          ELSIF NEW.visitas IS DISTINCT FROM OLD.visitas THEN RAISE EXCEPTION 'No autorizado a cambiar las visitas'; END IF;
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER trg_citas_guard BEFORE INSERT OR UPDATE ON citas FOR EACH ROW EXECUTE FUNCTION citas_guard();
      CREATE TRIGGER trg_clientas_guard BEFORE INSERT OR UPDATE ON clientas FOR EACH ROW EXECUTE FUNCTION clientas_guard();
    `);
    const migration=fs.readFileSync(path.join(__dirname,'../docs/fidelidad-migration.sql'),'utf8');
    await db.exec(migration);
    await db.exec(migration);
    const rows = async sql => (await db.query(sql)).rows;
    const visits = async () => (await rows(`SELECT visitas FROM clientas WHERE id='${customer}'`))[0].visitas;
    const appointment = async id => (await rows(`SELECT to_jsonb(c) AS cita FROM citas c WHERE id=${id}`))[0]?.cita;
    async function session(actor, fn, role='authenticated') {
        await db.exec('BEGIN');
        try {
            await db.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[actor||'']);
            await db.exec(`SET LOCAL ROLE ${role}`);
            const result=await fn();
            await db.exec('COMMIT');
            return result;
        } catch(e) { await db.exec('ROLLBACK'); throw e; }
    }
    const rpc=(tipo,datos,nonce=randomUUID(),actor=admin,role='authenticated') => session(actor,async()=>
      (await db.query('SELECT public.salon_operar($1,$2,$3::jsonb) AS resultado',[nonce,tipo,JSON.stringify(datos)])).rows[0].resultado,role);
    const change=async(id,fields,extra={})=>({id,antes:await appointment(id),cita:fields,...extra});
    const manual=async(accion)=>rpc('ajustar_sellos',{cliente_id:customer,accion,antes:await visits()});

    await t.test('only admins can call it or inspect the ledger',async()=>{
        await assert.rejects(rpc('ajustar_sellos',{},randomUUID(),null,'anon'),e=>e.code==='42501');
        await assert.rejects(rpc('ajustar_sellos',{},randomUUID(),customer),e=>e.code==='42501');
        assert.equal((await session(customer,()=>db.query('SELECT * FROM salon_movimientos'))).rows.length,0);
        await assert.rejects(session(customer,()=>db.query('SELECT * FROM salon_operaciones')),e=>e.code==='42501');
    });
    await t.test('completing and retrying credits once; stale changes fail',async()=>{
        const data=await change(100,{estado:'completada'}), nonce=randomUUID();
        const first=await rpc('guardar_cita',data,nonce);
        assert.equal(first.visitas,9);
        assert.deepEqual(await rpc('guardar_cita',data,nonce),first);
        assert.equal(await visits(),9);
        await assert.rejects(rpc('guardar_cita',data),/otra sesion/);
        await assert.rejects(rpc('guardar_cita',{...data,cita:{estado:'cancelada'}},nonce),/otra operacion/);
        await rpc('guardar_cita',await change(100,{precio:35}));
        assert.equal(await visits(),9);
    });
    await t.test('full card stays full until explicit redemption',async()=>{
        await rpc('guardar_cita',await change(101,{estado:'completada'}));
        await rpc('guardar_cita',await change(102,{estado:'completada'}));
        assert.equal(await visits(),10);
        await manual('canjear');
        assert.equal(await visits(),0);
        await assert.rejects(manual('canjear'),/diez sellos/);
        await rpc('guardar_cita',await change(103,{estado:'completada'}));
        assert.equal(await visits(),1);
    });
    await t.test('a redeemed card requires explicit preservation before reversing older work',async()=>{
        const data=await change(100,{estado:'cancelada'});
        await assert.rejects(rpc('guardar_cita',data),e=>e.hint==='CONFIRMAR_SIN_SELLO');
        assert.equal((await appointment(100)).estado,'completada');
        await rpc('guardar_cita',{...data,conservar_sellos:true});
        assert.equal(await visits(),1);
    });
    await t.test('current card reversal, recompletion and deletion are consistent',async()=>{
        await rpc('guardar_cita',await change(103,{estado:'cancelada'}));
        assert.equal(await visits(),0);
        await rpc('guardar_cita',await change(103,{estado:'completada'}));
        assert.equal(await visits(),1);
        const data={id:103,antes:await appointment(103)},nonce=randomUUID();
        await rpc('eliminar_cita',data,nonce);
        await rpc('eliminar_cita',data,nonce);
        assert.equal(await visits(),0);
        assert.equal(await appointment(103),undefined);
    });
    await t.test('legacy appointments keep balances unless explicitly reviewed',async()=>{
        await rpc('guardar_cita',await change(50,{precio:30}));
        const data=await change(50,{estado:'cancelada'});
        await assert.rejects(rpc('guardar_cita',data),e=>e.hint==='CONFIRMAR_SIN_SELLO');
        await rpc('guardar_cita',{...data,conservar_sellos:true});
        assert.equal(await visits(),0);
    });
    await t.test('direct legacy admin writes cannot bypass atomic loyalty',async()=>{
        await assert.rejects(session(admin,()=>db.query(`UPDATE clientas SET visitas=5 WHERE id='${customer}'`)),e=>e.code==='42501');
        await assert.rejects(session(admin,()=>db.query("UPDATE citas SET estado='completada' WHERE id=50")),e=>e.code==='42501');
    });
    await t.test('manual updates reject stale cards and idempotency protects creation',async()=>{
        await manual('sumar');
        await assert.rejects(rpc('ajustar_sellos',{cliente_id:customer,accion:'sumar',antes:0}),/otra sesion/);
        const data={id:null,antes:null,cita:{cliente_id:customer,fecha:'2030-01-02',hora:'09:00',duracion_minutos:30,estado:'completada',precio:25}};
        const nonce=randomUUID(), first=await rpc('guardar_cita',data,nonce);
        assert.deepEqual(await rpc('guardar_cita',data,nonce),first);
        assert.equal(await visits(),2);
        await assert.rejects(rpc('guardar_cita',data),e=>e.code==='23P01');
        assert.equal(await visits(),2);
    });
    await t.test('failure updating stamps rolls back the appointment and operation log',async()=>{
        await db.exec(`CREATE FUNCTION fail_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected failure'; END $$;
          CREATE TRIGGER zz_fail BEFORE UPDATE ON clientas FOR EACH ROW EXECUTE FUNCTION fail_test();`);
        const nonce=randomUUID(), before=await appointment(101);
        await assert.rejects(rpc('guardar_cita',{id:null,antes:null,cita:{cliente_id:customer,fecha:'2030-01-03',hora:'09:00',estado:'completada',duracion_minutos:30}},nonce),/injected failure/);
        assert.equal((await rows("SELECT * FROM citas WHERE fecha='2030-01-03'")).length,0);
        assert.equal((await rows(`SELECT * FROM salon_operaciones WHERE id='${nonce}'`)).length,0);
        assert.deepEqual(await appointment(101),before);
        await db.exec('DROP TRIGGER zz_fail ON clientas');
    });
    await t.test('manual booking without Auth profile never assigns stamps by phone',async()=>{
        const before=await visits();
        const result=await rpc('guardar_cita',{id:null,antes:null,cita:{cliente_id:null,nombre_cliente:'Invitada',telefono:'000',fecha:'2030-01-04',hora:'09:00',estado:'completada',duracion_minutos:30}});
        assert.match(result.aviso,/sin cuenta/);
        assert.equal(await visits(),before);
    });
    await t.test('deleting a customer handles appointment and ledger cascades together',async()=>{
        await rpc('eliminar_clienta',{cliente_id:customer});
        assert.equal((await rows('SELECT * FROM clientas')).length,0);
        assert.equal((await rows('SELECT * FROM salon_movimientos')).length,0);
        assert.equal((await rows('SELECT * FROM citas WHERE cliente_id IS NOT NULL')).length,0);
    });
});
